# Generated by Django 5.1.2 on 2024-10-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.IntegerField()),
                ('Contrasena', models.IntegerField()),
                ('Tipo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=45)),
                ('Telefono', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usario',
        ),
    ]
