# Generated by Django 5.1.2 on 2024-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_usuario_delete_usario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Contrasena',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Usuario',
            field=models.CharField(max_length=50),
        ),
    ]
