# Generated by Django 5.1.2 on 2024-10-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_usuario_contrasena_alter_usuario_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Tipo',
            new_name='Correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Telefono',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario',
        ),
    ]
