# Generated by Django 5.1.2 on 2024-10-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_delete_persona_rename_tipo_usuario_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Contrasena',
            new_name='CodigoSeguridad',
        ),
    ]
